image: Ubuntu1804 # образ для сборки

stack: node 16 # окружение

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

install:
  - npm install # команда установки зависимостей

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - npm build # команда сборки



deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name Andrey Bogdanov
  - git config --global user.email cesaress@yandex.ru
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=build --branch=gh-pages --force --verbose